tap "homebrew/cask"
tap "homebrew/core"
tap "neovim/neovim"
tap "sanemat/font"

brew "autoconf"
brew "automake"
brew "readline"
brew "python"
brew "awscli"
brew "cmake"
brew "colordiff"
brew "coreutils"
brew "direnv"
brew "gawk"
brew "ghq"
brew "git"
brew "pkg-config"
brew "jq"
brew "neovim"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "source-highlight"
brew "the_silver_searcher"
brew "tmux"
brew "wget"
brew "yarn", args: ["without-node"]
brew "zsh"
brew "gpg"
brew "go"
brew "dep"

brew "sanemat/font/ricty", args: ["with-powerline"]

cask "java"
cask "aquaskk"
cask "homebrew/cask-versions/iterm2-beta"

