[tools]
go = "latest"
node = "latest"
python = "latest"
rust = "latest"
deno = "latest"
bun = "latest"
yarn = "latest"
pnpm = "latest"
shfmt = "latest"
biome = "latest"
ruby = "latest"
ghc = "latest"
cabal = "latest"
