return {
  "folke/neodev.nvim",
  "folke/which-key.nvim",
  "tyru/eskk.vim",
  'vim-scripts/fencview.vim',
  'othree/eregex.vim',
  'nathanaelkane/vim-indent-guides',
  'airblade/vim-gitgutter',
  'tpope/vim-fugitive',
  'jiangmiao/auto-pairs',
  { "junegunn/fzf", dir = "~/.fzf", run = "./install --all" },
  'junegunn/fzf.vim',
  'tyru/caw.vim',
  'thinca/vim-quickrun',
  'ku1ik/vim-monokai',
  {
    'nvim-lualine/lualine.nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
  },
  { "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = {} },
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "neovim/nvim-lspconfig",
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-cmdline',
  'hrsh7th/nvim-cmp',
}
