export LANG=ja_JP.UTF-8
export RSENSE_HOME=$HOME/lib/rsense-0.3
export BUNDLER_EDITOR=vim
export PYTHONPATH=/usr/local/lib/python2.6/site-packages/
export BYOBU_PREFIX=/usr
export CABAL_BIN=$HOME/.cabal/bin
export PATH=/sbin:$HOME/local/bin:$PATH:$CABAL_BIN
export PATH=$PATH:/home/tett23/local/bin:/home/tett23/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
export ZSH=$HOME/.oh-my-zsh
plugins=(git)
