export DOTFILES=~/dotfiles

source $DOTFILES/zsh/exports.sh
source $DOTFILES/zsh/common.sh
source $DOTFILES/zsh/aliases.sh
source $DOTFILES/zsh/prompt.sh
[ -f ~/.fzf.zsh ] && source $HOME/.fzf.zsh
source $DOTFILES/zsh/fzf.sh
source $DOTFILES/zsh/modern-commands.sh
source $DOTFILES/zsh/anyenv.sh
source $DOTFILES/zsh/completions.sh
source $DOTFILES/zsh/docker.sh
source $DOTFILES/zsh/langs/rust.sh
source $DOTFILES/zsh/langs/js.sh
source $DOTFILES/zsh/langs/deno.sh
source $DOTFILES/zsh/langs/bun.sh
source $DOTFILES/zsh/langs/go.sh
source $DOTFILES/zsh/langs/ruby.sh
source $DOTFILES/zsh/langs/swift.sh
source $DOTFILES/zsh/langs/haskell.sh
source $DOTFILES/zsh/langs/scala.sh

# 言語/ツールは mise で一元管理。langs/* の後に activate して shims を最優先にする
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

source $DOTFILES/zsh/plugins.sh

## load user .zshrc configuration file
[ -f ~/.zshrc.mine ] && source ~/.zshrc.mine

eval "$(direnv hook zsh)"

