[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

# colors
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]] # linter
repo = 'w0rp/ale'

# powerline
[[plugins]] # なんかALEのlint情報をlightlineに出すのに必要らしい
repo = 'delphinus/lightline-delphinus'

[[plugins]]
repo = 'itchyny/lightline.vim'

# util
[[plugins]]
repo = 'kien/ctrlp.vim'

