[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

# colors
[[plugins]]
repo = 'tomasr/molokai'

# powerline
[[plugins]] # なんかALEのlint情報をlightlineに出すのに必要らしい
repo = 'delphinus/lightline-delphinus'

[[plugins]]
repo = 'itchyny/lightline.vim'

# util
[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]] # file encoding plugin
repo = 'vim-scripts/fencview.vim'

[[plugins]]
repo = 'othree/eregex.vim'

[[plugins]]
repo = 'vim-scripts/grep.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

### language plugins

[[plugins]] # linter
repo = 'w0rp/ale'

# ruby
[[plugins]]
repo = 'vim-scripts/rails.vim'

[[plugins]]
repo = 'vim-scripts/ruby-matchit'

# markdown
[[plugins]]
repo = 'tpope/vim-markdown'

# go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_fmt_command = 'goimports'
  let s:goargs = go#package#ImportPath(expand('%:p:h'))
'''

[[plugins]]
repo = 'jnwhiteh/vim-golang'

[[plugins]]
repo = 'zchee/deoplete-go'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# javascript
[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'

[[plugins]]
repo = 'othree/yajs.vim'

# coffee
[[plugins]]
repo = 'kchmck/vim-coffee-script'

# html
[[plugins]]
repo = 'mattn/emmet-vim'

# jade
[[plugins]]
repo = 'digitaltoad/vim-jade'

# stylus
[[plugins]]
repo = 'wavded/vim-stylus'

# c++
[[plugins]]
repo = 'osyo-manga/vim-marching'

[[plugins]]
repo = 'msanders/cocoa.vim'
